services:
  mc:
    container_name: mcv-docker-0.1
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: NEOFORGE
      VERSION: "1.20.1"
      NEOFORGE_VERSION: "47.1.99"
      MEMORY: "6G"
      MAX_MEMORY: "8G"
      MAX_TICK_TIME: "-1"
      ENABLE_AUTOPAUSE: "true"
      AUTOPAUSE_TIMEOUT_EST: "360"
      AUTOPAUSE_TIMEOUT_KN: "30"
      ONLINE_MODE: "false"
      ALLOW_FLIGHT: "true"
      MAX_PLAYERS: "8"
      SEED: ""
      MOTD: "A Movie minecraft server"
      # ICON: /data/server-icon.png
      SPAWN_PROTECTION: "0"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - I:\Docker\120-neo:/data
      # - /home/nekooitine/MC-Server/Docker-server/data:/data
    restart: on-failure:3